[build]
  publish = "public"
  functions = "netlify/functions"
  command = "echo 'Static site - no build needed'"

[build.environment]
  NODE_VERSION = "18"

# Redirecionamentos para API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirecionamento para WebSocket (simulação REST para produção)
[[redirects]]
  from = "/ws/*"
  to = "/.netlify/functions/websocket/:splat"
  status = 200

# Fallback para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Headers para arquivos CSS e JS
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"